[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PRISMA_GENERATE_DATAPROXY = "false"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Prisma specific configuration
[build.environment]
  PRISMA_CLI_BINARY_TARGETS = "native,linux-musl"
