[build]
  command = "npm run build:netlify"
  publish = ".next/standalone"

[build.environment]
  NODE_VERSION = "18"
  PRISMA_GENERATE_DATAPROXY = "false"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"
  PRISMA_CLI_BINARY_TARGETS = "native,linux-musl"

# Next.js specific redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
