[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PRISMA_GENERATE_DATAPROXY = "false"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"
  PRISMA_CLI_BINARY_TARGETS = "linux-musl"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The @netlify/plugin-nextjs plugin will handle all routing automatically

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
